(function(g){var window=this;var L2=function(a){var b={languageCode:a.u,languageName:a.w,displayName:g.Rz(a),kind:a.A,name:a.B,id:a.H,is_servable:a.D,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},M2=function(a){return a.o?a.o.languageCode:a.u},xpa=function(a,b){var c=new g.Qz;
c.u=a.u;c.w=a.w;c.B=a.B;c.A=a.A;c.isDefault=!1;c.D=a.D;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},ypa=function(){this.u=[];
this.o=[]},N2=function(a,b){return b?a.o.concat(a.u):a.o},O2=function(a,b){switch(b.A){case "asr":var c=a.u;
g.Ua(c,(0,g.x)(b.rq,b))||c.push(b);break;default:c=a.o,g.Ua(c,(0,g.x)(b.rq,b))||c.push(b)}},P2=function(a){g.E.call(this);
this.Xa=a;this.u=new ypa;this.B=[]},Q2=function(a,b,c){P2.call(this,a);
this.o=null;this.B=b.Tt;this.w=c},R2=function(){this.o=[]},S2=function(a,b,c,d,e,f){g.E.call(this);
this.J=a;this.w=b;this.U=b.O();this.B=new R2;this.o=null;this.D=d;this.K=f;this.u=this.A=null;this.P=c;this.C=e||!1;this.G=new g.J(this.cw,1E3,this);g.H(this,this.G);this.H=new g.Q(this);g.H(this,this.H);this.H.M(b,"SEEK_COMPLETE",this.Jw);this.Jw();this.cw()},T2=function(a,b){b-=a.w.vb();
var c=a.o;a.o=g.Sa(a.P.sf(b).o);c!=a.o&&a.K&&a.K()},U2=function(a,b){var c=g.Gw(g.Rw(b,a.J,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Wp(c,d,3,100).then((0,g.x)(a.YJ,a));a.A=b;c=a.B;d=a.A.o[0].u;var e=g.kb(c.o,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.o[e-1]&&e<c.o.length&&1==c.o[e]-d?(g.$a(c.o,e),g.$a(c.o,e-1)):0<e&&1==d-c.o[e-1]?c.o[e-1]=d:e<c.o.length&&1==c.o[e]-d?c.o[e]=d:(g.gb(c.o,e,0,d),g.gb(c.o,e+1,0,d)))},V2=function(a,b){P2.call(this,b.O());
this.o=a;this.D=b;this.w=null;this.A=!1;this.C=g.zz(this.D.O())&&!this.o.u},W2=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.AP(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Qz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},zpa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},X2=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.AP(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},Y2=function(a,b,c,d,e){P2.call(this,e||null);
c=c||g.dp(a).hl||"";c=c.split("_").join("-");this.A=g.fp(a,{hl:c});this.w=b;this.C=!!d;this.D={};this.o=null},Z2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.KD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.w=f;this.o=k},$2=function(a,b,c,d,e){g.KD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},b3=function(a){a=void 0===a?{}:a;
var b="_"+a3++;return new $2(0,0x8000000000000,0,b,a)},d3=function(a,b,c,d,e,f){var k={};
g.Oa(k,b);g.Oa(k,a.params);g.Oa(k,c);var l={};g.Oa(l,b.ub);a.params.ub&&g.Oa(l,a.params.ub);g.Oa(l,c.ub);k.ub=l;g.W.call(this,{F:"div",I:"caption-window",N:{id:"caption-window-"+a.id,dir:1==k.pe?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},L:[{F:"span",I:"captions-text",N:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.T=!1;this.A=a;this.ca=this.V=null;this.La=e;this.Ka=f;this.G=null;this.aa=.96*e;this.xa=.96*f;this.w=k;this.Ga=c;this.C=this.u["captions-text"];this.Aa=
null!=this.C.style["box-decoration-break"]||null!=this.C.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.la=this.Z*c3(l);a=new g.DL(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.qF,this);a.subscribe("dragmove",this.pF,this);a.subscribe("dragend",this.oF,this);this.wa=this.na=0;b="";this.w.windowOpacity&&(a=g.c_(this.w.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.w.windowOpacity+")");a={"background-color":b,display:!1===this.w.isVisible?"none":"","text-align":Apa[this.w.textAlign]};
this.Aa&&(a["border-radius"]=b?this.la/8+"px":"");if(this.B=2==this.A.params.pe||3==this.A.params.pe)b=this.element,c="vertical-rl",1==this.w.Cz&&(c="vertical-lr"),g.Gd&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.ag(b,"-o-writing-mode",c),g.ag(b,"-webkit-writing-mode",c),g.ag(b,"writing-mode",c),g.ag(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3==this.A.params.pe&&(g.ag(b,"text-orientation",""),g.ag(b,"transform","rotate(180deg)"));g.ag(this.element,a);switch(this.w.Tf){case 0:case 1:case 2:g.K(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},c3=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},e3=function(a,b){var c={},d=b.background?b.background:a.w.ub.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.w.ub.backgroundOpacity;d=g.c_(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*c3(b)+"px";d=1;e=b.color||a.w.ub.color;if(b.color||null!=b.textOpacity)e=g.c_(e),d=null==b.textOpacity?a.w.ub.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.cu&&(k=e=b.cu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Gp()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.w.ub.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ke&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.fD&&(c.visibility="hidden");1==b.hD&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Iu||g.Bz,3==a.A.params.pe?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.oe||2==b.oe||3==b.oe||4==b.oe||5==b.oe)if(g.Iu)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.oe){case 4:case 3:c["text-emphasis-position"]="under left";c["webkit-text-emphasis-position"]=
"under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},f3=function(a){a.G=g.Nd("SPAN");
g.ag(a.G,{display:"block"});g.K(a.G,"caption-visual-line");a.C.appendChild(a.G)},g3=function(a,b){var c=g.Nd("SPAN");
g.ag(c,{display:"inline-block","white-space":"pre-wrap"});g.ag(c,e3(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.ag(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ag(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},h3=function(a,b,c){a.T=a.T||!!c;
var d={};g.Oa(d,a.w.ub);g.Oa(d,c||b.o);g.Oa(d,a.Ga.ub);(c=!a.G)&&f3(a);for(var e=a.V&&a.ca&&g.Yb(d,a.ca)?a.V:g3(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.w,n=k[l];m&&!c?(f3(a),e=g3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Od(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.Iu||!g.eg(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.eg(n.children[2],"text-emphasis-position")&&(m=a.B?"padding-left":"padding-bottom"),g.Id?
g.ag(e,m,"1em"):g.ag(e,m,"0.5em")))}a.ca=d;a.V=e;a.D.push(b)},i3=function(){},k3=function(){this.A=this.u=this.mode=this.w=0;
this.B=new j3(this);this.C=new j3(this);this.o=[];this.clear()},Bpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{ul:a,
vl:b,result:0};a=l3[a];b=l3[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{ul:a,vl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ul:a,vl:b,result:2};return{ul:a,vl:b,result:3}},Cpa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,m3(a.B,b,c,d))},Dpa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?Cpa(a,d.Vt,d.Wt,b):1==d.type&&a.w&496&&m3(a.C,d.Vt,d.Wt,b)}a.o.length=0},n3=function(){this.o=0},o3=function(){this.u=this.w=this.o=0},p3=function(){this.timestamp=this.Rd=0},q3=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new p3}this.o=this.u=this.row=0;this.style=new n3;this.B=a;this.A=0},r3=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.w[m][q];
if(0!=t.Rd){0==c&&(c=m,d=q);n=String.fromCharCode(t.Rd);var v=t.timestamp;v<e&&(e=v);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Rd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.w[k][m],t=q.Rd,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Ipa=function(a,b){switch(a){case 0:return Epa[(b&127)-32];
case 1:return Fpa[b&15];case 2:return Gpa[b&31];case 3:return Hpa[b&31]}return 0},s3=function(a){return a.w[a.row][a.u]},t3=function(a,b,c){2<=b&&1<a.u&&(--a.u,s3(a).Rd=0);
var d=s3(a);d.timestamp=a.B.u+0;d.Rd=Ipa(b,c);32>a.u&&a.u++},u3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].Zf(a.w[c+e][f])},v3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},w3=function(a){a.row=0<a.o?a.o:1;
a.u=1;v3(a,0,15)},x3=function(a){this.A=a;
this.B=0;this.style=new n3;this.C=new q3(a);this.D=new q3(a);this.G=new q3(a);this.u=this.C;this.w=this.D;this.o=this.u},y3=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:r3(d,c),w3(a.u),w3(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(r3(d,c),v3(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},z3=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},A3=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},j3=function(a){this.u=a;
this.o=new o3;this.B=0;this.w=new x3(a);this.C=new x3(a);this.A=this.w},m3=function(a,b,c,d){a.o.update();
b=Bpa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ul;c=b.vl;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&t3(a,0,b),c&96&&t3(a,0,c),0!=b&&0!=c&&3==a.style.o&&r3(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;u3(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));v3(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:t3(b.o,0,32);break a;case 48:57==c?(d=b.o,s3(d).Rd=0,32>d.u&&d.u++):t3(b.o,1,c&15)}break;case 2:c&32&&t3(b.o,2,c&31);break;case 3:c&32&&t3(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:z3(b);break;case 33:d=
b.o;1<d.u&&(--d.u,s3(d).Rd=0);break;case 36:d=b.o;b=s3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:y3(b,2,d);break;case 38:y3(b,3,d);break;case 39:y3(b,4,d);break;case 40:t3(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);w3(d);A3(b);break;case 43:A3(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:r3(a,d)}v3(a,0,15);break;case 45:b:{a=
b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;r3(a,d);u3(a,b,b+1,a.o-1);v3(a,a.row,1)}break;case 46:v3(b.w,0,15);break;case 47:r3(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,z3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},B3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Wc){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var v=g.Gp();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=v?g.Nd("DIV"):g.Nd("RUBY");l=l.textContent;var z=g.Nd("SPAN");z.textContent=l;f.appendChild(z);n.getAttribute("p");z=v?g.Nd("DIV"):g.Nd("RP");l=n.textContent;z.textContent=l;f.appendChild(z);k=k[q.getAttribute("p")];l=q.textContent;q=v?g.Nd("DIV"):g.Nd("RT");q.textContent=l;f.appendChild(q);l=k.Wc;if(10==l||11==l||12==l||13==l||14==l)if(g.ag(q,"text-emphasis",
"filled circle"),g.ag(q,"webkit-text-emphasis","filled circle"),k.Wc==k.Wc==11||13==k.Wc)g.ag(q,"webkit-text-emphasis-position","under left"),g.ag(q,"text-emphasis-position","under left");q=!0;if(4==k.Wc||7==k.Wc||12==k.Wc||14==k.Wc)g.ag(f,"ruby-position","over"),g.ag(f,"-webkit-ruby-position","before");else if(5==k.Wc||6==k.Wc||11==k.Wc||13==k.Wc)g.ag(f,"ruby-position","under"),g.ag(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;t=v?g.Nd("DIV"):g.Nd("RP");t.textContent=
l;f.appendChild(t);v&&(v=q,g.ag(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.ag(t,"display","none"),t=t.nextElementSibling,g.ag(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ag(f.lastElementChild,"display","none"),v?(g.ag(f,"padding-top","0.6em"),g.ag(t,"top","0")):(g.ag(f,"padding-bottom","0.6em"),g.ag(t,"bottom","0")));return new Z2(a,b,e,c,f,d,m)}switch(m.Wc){case 9:case 10:m.oe=
1;break;case 11:m.oe=2;break;case 12:m.oe=3;break;case 13:m.oe=4;break;case 14:m.oe=5}return new Z2(a,b,e,c,l.textContent||"",d,m)},C3=function(){g.E.apply(this,arguments)},D3=function(a){C3.call(this);
this.w={};this.H={};this.J={};this.B="_"+a3++;this.C=a;this.G={};this.u=this.o=null;this.D=!0},E3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},F3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},G3=function(a,b){var c=E3(a,b);
return void 0!=c?c:null},I3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return H3.test(c),c},J3=function(a,b){var c={},d=b.getAttribute("ws");
g.Oa(c,d?a.J[d]:a.C);d=G3(b,"mh");null!=d&&(c.jq=d);d=G3(b,"ju");null!=d&&(c.textAlign=d);d=G3(b,"pd");null!=d&&(c.pe=d);d=G3(b,"sd");null!=d&&(c.Cz=d);d=I3(b,"wfc");null!=d&&(c.windowColor=d);d=E3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},K3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Oa(c,a.H[d]);d=G3(b,"ap");null!=d&&(c.Tf=d);d=E3(b,"cc");null!=d&&(c.Il=d);d=E3(b,"ah");null!=d&&(c.Le=d);d=E3(b,"rc");null!=d&&(c.zk=d);d=E3(b,"av");null!=d&&(c.Dg=d);return c},L3=function(a,b,c,d){var e={};
g.Oa(e,K3(a,b));g.Oa(e,J3(a,b));d?g.Yb(e,a.C)?(d=a.B,e=a.C):d="_"+a3++:d=b.getAttribute("id")||"_"+a3++;a=E3(b,"t")+c;b=E3(b,"d")||0x8000000000000;if(2==e.pe||3==e.pe)c=e.zk,e.zk=e.Il,e.Il=c;return new $2(a,b,0,d,e)},M3=function(a,b,c,d,e,f,k){d3.call(this,a,b,c,d,e,f,k);
this.type=1},N3=function(a,b,c){this.D=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},O3=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},P3=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},Q3=function(a,b){C3.call(this);
this.u=a;this.track="CC3"==b.w?4:0;this.o=new k3;this.o.w=1<<this.track},S3=function(a){if("string"===typeof a)return!1;
a=new N3(a,8,0);return R3(a)},R3=function(a){if(!(a.o<a.u.byteLength)||1380139777!=P3(a))return!1;
a.version=O3(a);if(1<a.version)return!1;O3(a);O3(a);O3(a);return!0},T3=function(a,b,c,d,e,f,k){d3.call(this,a,b,c,d,e,f,k);
g.K(this.element,"ytp-caption-window-rollup");this.type=2;this.H=[];this.K=this.J=this.fa=0;this.P=NaN;this.ya=0;this.Ca=null;this.ea=new g.J(this.dK,433,this);g.H(this,this.ea);g.ag(this.element,"overflow","hidden")},Jpa=function(a,b){return(a.B?b.offsetHeight:b.offsetWidth)+1},Kpa=function(a){if(isNaN(a.P)){var b=a.w.Il;
if(b){var c=g.Nd("SPAN");g.Xd(c,"\u2013".repeat(b));g.ag(c,e3(a,a.w.ub));a.C.appendChild(c);a.P=c.offsetWidth;a.C.removeChild(c)}else a.P=0}return a.P},Lpa=function(a,b){if(!b)return"";
a.B&&1!=a.A.params.Cz&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},U3=function(a){a.H=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.A.params.zk,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.J=d;a.K=Math.max(Kpa(a),a.ya,Jpa(a,a.C))},Mpa=function(a,b){U3(a);
var c=a.H.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.J-c;if(c!=a.fa){var d=0<c&&0==a.fa;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.Xm(a.ea));g.ag(a.C,"transform",Lpa(a,c));a.fa=c}U3(a)},V3=function(){C3.call(this)},W3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ke=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new Z2(b,c,d,e.id,q.nodeValue,f||0<n,g.Wb(l)?void 0:l);m.push(q);var t=e;g.H(t,q);t.o.push(q)}else t={},g.Oa(t,l),W3(a,b,c,d,e,!0,q,t,m)}},X3=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},Y3=function(a,b,c,d){d=Object.assign({jq:0},d);
return new $2(a,b,c,"_"+a3++,d)},Z3=function(a){g.E.call(this);
this.u=a;this.o=null},b4=function(a){g.zP.call(this,a);
this.w=a.O();this.S=a.getVideoData();this.wa=g.DK(a);this.T=a;var b=null,c=g.Mn("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.wn(c));this.ca=b;this.A={ub:{}};this.C={ub:{}};this.J=[];this.U={};this.da={};this.K=!1;this.la=g.BP(this.S,this.T);this.xa=!!this.S.captionTracks.length;this.ya=!!this.S.hj;this.fa="3"==this.w.controlsType;b=a.app.B;c=!(!b||!b.Nk());this.na=!(!b||!b.Ch());this.B=this.fa&&c&&!this.la;this.H=!this.B&&this.fa&&this.na&&this.la;this.u=this.D=this.G=this.V=this.ea=
null;this.Z=new Z3(this.w);g.H(this,this.Z);c=b=this.o=null;this.B||(b=new g.Um(this.Sz,void 0,this),g.H(this,b),c=new g.J(this.GL,2E3,this),g.H(this,c));this.aa=b;this.oa=c;this.P=new g.Q(this);g.H(this,this.P);this.B||this.P.M(a,"resize",this.ts);this.P.M(a,"onPlaybackAudioChange",this.GH);this.P.M(a,g.ND("captions"),this.pE,this);this.P.M(a,"crx_captions",this.qE,this);$3(this,a4(this,"display-settings")||{})},c4=function(a){if(1==a.w.Wf||1==a.S.Wf||"alwayson"==g.zC(a.S,"yt:cc"))return!0;
if(2==a.w.Wf){var b=a4(a,"module-enabled");if(null!=b)return!!b}if(a.S.captionTracks.length)var c=a.player.getAudioTrack().Lo;return"ON"==c||"on"==g.zC(a.S,"yt:cc")},d4=function(a,b){if(a.o&&(void 0===b||!b)||!a.S.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Tl||"FORCED_ON"==c.Lo},f4=function(a,b){if(a.u){if(a.D&&a.D.o)return a.D.o;
var c=b;c||(c=a.ya?!1:a.xa?!1:!0);c=N2(a.u.u,c);for(var d=[a.S.captionsLanguagePreference,a.w.captionsLanguagePreference,g.zC(a.S,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(M2(c[f])==d[e])return c[f];return a.D&&a.D.Uo?a.D.Uo:(d=c.find(function(k){return k.isDefault}))?d:c[0]||e4(a)}return null},e4=function(a){return a.D&&a.D.Tl},g4=function(a){var b=e4(a);
return!!b&&a.o==b},h4=function(a,b){for(var c=a.T.app.B.Za().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},j4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&i4(a,"module-enabled",!!b));a.o=b;d4(a)&&(a.o=e4(a));a.load()},Npa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.jq?b.params.jq:1<b.o.length?1:0){case 1:return new M3(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new T3(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new d3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},$3=function(a,b,c){var d=k4.ub;
a.A={};g.Oa(a.A,k4);a.A.ub={};g.Oa(a.A.ub,d);a.C={ub:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;H3.test(f);e.ub.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;H3.test(f);e.ub.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||k4.windowColor;H3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ub.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.ub.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Ke?3:d.bold?1:d.Ke?2:0);f=f.ub;switch(e){case 1:f.bold=!0;delete f.Ke;break;case 2:delete f.bold;f.Ke=!0;break;case 3:f.bold=!0;f.Ke=!0;break;default:delete f.bold,delete f.Ke}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ub.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=k4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.A;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.ub.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ub.fontFamily=f;a.loaded&&a.ts();c&&i4(a,"display-settings",b)},m4=function(a,b){if(b&&!a.G){var c=b3({pe:0,
lang:"en"});a.G=[c,new Z2(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.RK(a.player,a.G)}else!b&&a.G&&(l4(a,a.G),a.G=null)},l4=function(a,b){g.nT(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.ab(this.J,c)},a);
a.aa.bi()},a4=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},i4=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.Qz.prototype.rq=g.ca(11,function(a){return a?this.toString()==a.toString():!1});
g.dv.prototype.hm=g.ca(10,function(a){return(a=this.eg(a))?a.o:0});
g.ix.prototype.hm=g.ca(9,function(){return 0});
g.Ht.prototype.ij=g.ca(8,function(){for(var a=g.yd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Sd(a[b])});
g.oR.prototype.ij=g.ca(7,function(){this.o.ij()});
g.Ht.prototype.Nk=g.ca(6,function(){return!!this.o.textTracks});
g.oR.prototype.Nk=g.ca(5,function(){return this.o.Nk()});
g.Ht.prototype.dj=g.ca(4,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.oR.prototype.dj=g.ca(3,function(a){this.o.dj(a)});
g.xt.prototype.Ch=g.ca(2,function(){});
g.Ht.prototype.Ch=g.ca(1,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.oR.prototype.Ch=g.ca(0,function(){return this.o.Ch()});
var Opa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,H3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(P2,g.E);P2.prototype.Dy=function(){return!1};
P2.prototype.Y=function(){this.Eg();g.E.prototype.Y.call(this)};
g.r(Q2,P2);Q2.prototype.hq=function(a,b,c){b=this.Bj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Eg();this.o=g.xp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
Q2.prototype.iq=function(a){if(this.w)for(var b=g.p(this.w.captionTracks),c=b.next();!c.done;c=b.next())O2(this.u,c.value);a()};
Q2.prototype.Bj=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b)g.Gp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=M2(a));return g.fp(c,d)};
Q2.prototype.Eg=function(){this.o&&this.o.abort()};
R2.prototype.contains=function(a){a=g.kb(this.o,a);return 0<=a||0>a&&1==(-a-1)%2};
R2.prototype.length=function(){return this.o.length/2};
g.r(S2,g.E);g.h=S2.prototype;g.h.Y=function(){g.E.prototype.Y.call(this);this.u&&this.u.cancel()};
g.h.Jw=function(){T2(this,this.w.getCurrentTime())};
g.h.reset=function(){this.B=new R2;this.u&&(this.u.cancel(),this.u=null)};
g.h.cw=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Ef(a);!a||this.u||this.o&&30<this.o.startTime-this.w.getCurrentTime()||(a=this.o,a=a.o.ti(a),a.o[0].duration?(this.B.contains(a.o[0].u)||U2(this,a),this.o=g.Sa(a.o)):!g.R(this.U.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.w.vb()<this.w.getCurrentTime()&&T2(this,this.w.getCurrentTime()));this.G.start()};
g.h.YJ=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.nx(a);c?(a=g.Rw(this.A,this.J,{}),b=this.A,g.Nw(b.u,a,c),b.requestId=a.get("req_id"),U2(this,this.A)):(b||null===this.D||(c=this.A.o[0],this.C?this.D(a.response,1E3*(c.startTime+this.w.vb())):this.D(a.responseText,1E3*(c.startTime+this.w.vb()))),this.u=this.A=null)};
g.r(V2,P2);g.h=V2.prototype;g.h.hq=function(a,b,c){this.Eg();b=zpa(this,a.getId());b||(b=a.u,b=this.o.u?X2(this,b,"386"):X2(this,b));if(b){var d=1E3*(b.index.hm(b.index.ie())-b.index.Hc(b.index.ie()));this.w=new S2(new g.Iw,this.D,b,function(e,f){c(e,a,f,d)},this.C||g.Js(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.Dy=function(){var a=this.A;this.A=!1;return a};
g.h.iq=function(a){var b;this.C?b=[new g.Qz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Qz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?W2(this,"386"):W2(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())O2(this.u,c.value);a()};
g.h.Eg=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.Bj=function(){return""};
g.r(Y2,P2);Y2.prototype.hq=function(a,b,c){b=this.Bj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Eg();this.o=g.xp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
Y2.prototype.iq=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.fp(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),v="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
O2(this.u,new g.Qz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:v,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.D[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Eg();this.o=g.xp(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
Y2.prototype.Bj=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.u,name:a.getName(),kind:a.A,fmt:b};a.o&&(d.tlang=M2(a));return c=g.fp(c,d)};
Y2.prototype.Eg=function(){this.o&&this.o.abort()};var Apa=["left","right","center","justify"];var k4={windowColor:"#080808",windowOpacity:0,textAlign:2,Tf:7,Le:50,Dg:100,ub:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(Z2,g.KD);Z2.prototype.toString=function(){return g.KD.prototype.toString.call(this)};g.r($2,g.KD);$2.prototype.toString=function(){return g.KD.prototype.toString.call(this)};
var a3=0;g.r(d3,g.W);g.h=d3.prototype;g.h.qF=function(a,b){var c=g.qg(this.element,this.element.parentElement);this.na=a-c.x;this.wa=b-c.y;g.K(this.element,"ytp-dragging")};
g.h.pF=function(a,b){var c=g.tg(this.element),d=a-this.na-.02*this.La,e=b-this.wa-.02*this.Ka,f=(d+c.width/2)/this.aa*3;f=Math.floor(g.ld(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.ld(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.aa;d=100*g.ld(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.ld(c,0,1);this.A.params.Tf=l;this.A.params.Dg=c;this.A.params.Le=d;this.w.Tf=l;this.w.Dg=c;this.w.Le=d;this.cz()};
g.h.oF=function(){g.hn(this.element,"ytp-dragging")};
g.h.cz=function(){this.zh(this.D)};
g.h.zh=function(a){var b=Math.min(this.Tu(),this.aa),c=this.Su(),d="";3==this.A.params.pe&&(d="rotate(180deg)");g.ag(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Bo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.w.Le+2;d=this.w.Tf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.w.Dg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ag(this.element,a)};
g.h.Bo=function(a){var b;for(b=0;b<a.length&&a[b]==this.D[b];b++);if(this.T||this.D.length>b)b=0,this.T=!1,this.D=[],this.G=this.ca=this.V=null,g.Qd(this.C);for(;b<a.length;b++)h3(this,a[b])};
g.h.Tu=function(){return 0};
g.h.Su=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};i3.prototype.B=function(){};k3.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
k3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var l3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];n3.prototype.set=function(a){this.o=a};
n3.prototype.get=function(){return this.o};
o3.prototype.clear=function(){this.o=0};
o3.prototype.update=function(){this.o=2==this.o?1:0};
o3.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
p3.prototype.Zf=function(a){this.Rd=a.Rd;this.timestamp=a.timestamp};
p3.prototype.reset=function(){this.timestamp=this.Rd=0};
q3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
q3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.Rd?a+"_":a+String.fromCharCode(d.Rd)}a+="\n"}return a};
q3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var Epa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Fpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Gpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Hpa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];x3.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.D;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
j3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(C3,g.E);C3.prototype.reset=function(){};g.r(D3,C3);D3.prototype.reset=function(){this.G={};this.u=this.o=null;this.D=!0};
D3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.w,l={},m=c.getAttribute("p");m&&g.Oa(l,this.w[m]);m=F3(c,"b");null!=m&&(l.bold=
m);m=F3(c,"i");null!=m&&(l.Ke=m);m=F3(c,"u");null!=m&&(l.underline=m);m=G3(c,"et");null!=m&&(l.charEdgeStyle=m);m=G3(c,"of");null!=m&&(l.offset=m);m=I3(c,"bc");null!=m&&(l.background=m);m=I3(c,"ec");null!=m&&(l.cu=m);m=I3(c,"fc");null!=m&&(l.color=m);m=G3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=E3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=E3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=E3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=G3(c,"rb");null!=m&&10!=m&&0!=m&&(l.Wc=10<m?m-1:m);
m=G3(c,"hg");null!=m&&(l.hD=m);c=G3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.oe=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=J3(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=K3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=L3(this,d,e,!1);g.H(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.B;m=!!F3(d,"a");n=(E3(d,"t")||0)+n;var q=E3(d,"d")||5E3;m||(!this.D&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,v=this.w[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.D=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var B=z[C],G=void 0;0<C&&(m=!0);var I=void 0;1==B.nodeType&&(I=B);if(I&&"s"==I.tagName){if((B=this.w[I.getAttribute("p")])&&B.Wc&&(1==B.Wc?(B=z.slice(C,
C+4),4==B.length&&(G=B3(n,q,l,m,t,B,this.w),C+=3)):G=B3(n,q,l,m,t,[I],this.w)),!G){var F=I;G=n;I=q;B=l;var M=m,U=t,fa=F.textContent?F.textContent:"",Ca=this.w[F.getAttribute("p")];F=E3(F,"t")||0;G=new Z2(G+F,I-F,U,B,fa,M,Ca)}}else G=new Z2(n,q,t,l,B.textContent||"",m,v);k.push(G);this.u=G}if(0<k.length)for(k[0].windowId==this.B&&(this.o=L3(this,d,e,!0),g.H(this,this.o),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.H(l,k),l.o.push(k),c.push(k)}e=c}else e=
[];return e};g.r(M3,d3);M3.prototype.Bo=function(a){var b=this.A.o;d3.prototype.Bo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Oa(d,c.o);g.Oa(d,Ppa);var e=c.o;var f=d}h3(this,c,d)}};
var Ppa={fD:!0};g.r(N3,i3);N3.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+a3++;c=c/1E3-this.D;d=d/1E3-this.D;a=new $2(c,d-c,5,f,{textAlign:0,Tf:0,Le:2.5*b,Dg:5.33*a});e=new Z2(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(Q3,C3);Q3.prototype.A=function(a){a=new N3(a,a.byteLength,this.u);if(R3(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=P3(a)*(1E3/45):1==a.version&&(a.A=4294967296*P3(a)+P3(a)),a.C=O3(a);0<a.C;a.C--){var b=O3(a),c=O3(a),d=O3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,Vt:c,Wt:d,order:b.o.length}))}Dpa(this.o,a);return a.w}return[]};
Q3.prototype.reset=function(){this.o.clear()};g.r(T3,d3);g.h=T3.prototype;g.h.cz=function(){g.Ym(this.ea)};
g.h.dK=function(){g.hn(this.element,"ytp-rollup-mode");this.zh(this.Ca,!0)};
g.h.Su=function(){return this.B?this.K:this.J};
g.h.Tu=function(){return this.B?this.J:this.K};
g.h.zh=function(a,b){this.Ca=a;if(this.A.params.zk){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.ya=this.K;this.J=this.K=0;d3.prototype.zh.call(this,a);Mpa(this,b);d3.prototype.zh.call(this,a)}else d3.prototype.zh.call(this,a)};g.r(V3,C3);
V3.prototype.A=function(a,b){for(var c=[],d=a.split(Qpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Rpa.test(f)){var l=n4.exec(f);if(l&&4<=l.length){var m=X3(l[1]),n=X3(l[2])-m;m+=k;var q,t=q=void 0,v=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.p(C?C.split(" "):[]);for(var B=C.next();!B.done;B=C.next())if(B=B.value.split(":"),2==B.length){var G=B[1];switch(B[0]){case "line":B=G.split(",");B[0].endsWith("%")&&(z=B[0],l.Dg=Number.parseInt(z,10),2==B.length&&(v=B[1].trim()));break;case "position":B=G.split(",");
t=B[0];l.Le=Number.parseInt(t,10);2==B.length&&(q=B[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Dg=100,v||(v="end"));if(!t)switch(l.textAlign){case 0:l.Le=0;break;case 1:l.Le=100;break;default:l.Le=50}t=0;switch(v){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Tf=0>t||8<t?7:t;q=l;f=f.substring(n4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=Y3(m,n,5,t),n=new Z2(m,n,5,k.id,q,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),g.H(k,n),k.o.push(n);else for(v=q.split(Spa),1==v.length?(q=5,t=Y3(m,n,q,t)):(z=q=6,t=Object.assign({Il:32},t),t=new $2(m,n,z,"_"+a3++,t)),c.push(t),z=m,l=0;l<v.length;l++)C=v[l],0==l%2?(B=g.d_("<html>"+C+"</html>"),B.getElementsByTagName("parsererror").length?
(G=B.createElement("span"),G.appendChild(B.createTextNode(C))):G=B.firstChild,W3(this,z,n-(z-m),q,t,0<l,G,f,c)):z=X3(C)+k}n4.lastIndex=0}}return c};
var Rpa=/^NOTE/,Qpa=/(?:\r\n|\r|\n){2,}/,n4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Spa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(Z3,g.E);Z3.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
Z3.prototype.reset=function(){this.o&&this.o.reset()};
Z3.prototype.Y=function(){this.clear();g.E.prototype.Y.call(this)};g.r(b4,g.zP);g.h=b4.prototype;g.h.Y=function(){if(this.B||this.H){var a=this.T.app.B;a&&a.ij()}else m4(this,!1);g.zP.prototype.Y.call(this)};
g.h.load=function(){g.zP.prototype.load.call(this);var a=!g.R(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.D=this.player.getAudioTrack();if(this.u)this.o&&(this.Z.clear(),this.B?h4(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.hq(this.o,"srv3",(0,g.x)(this.MK,this)),!a||this.B||this.H||g4(this)||this.player.ka("captionschanged",L2(this.o))),a||(this.o&&!g4(this)?this.player.ka("captionschanged",L2(this.o)):this.player.ka("onCaptionsTrackListChanged"));else{var b;
this.la?b=new V2(this.S.ia,this.player):this.xa?b=new Q2(this.w,this.S,this.player.getAudioTrack()):b=new Y2(this.S.hj,this.S.videoId,this.S.captionsLanguagePreference||this.w.captionsLanguagePreference||g.zC(this.S,"yt:cc_default_lang")||this.w.Tb,this.S.Jo,this.w);this.u=b;g.H(this,this.u);b.iq((0,g.x)(this.LK,this))}};
g.h.unload=function(){this.B&&this.o?h4(this,!1):(this.oa&&g.Zm(this.oa),g.FQ(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Eg(),this.Z.clear(),this.G&&g.RK(this.player,this.G),this.ts());g.zP.prototype.unload.call(this);var a=g.V(this.player.app);a&&g.iI(a.B);this.player.ka("captionschanged",{})};
g.h.create=function(){(this.fa?this.B||this.H:d4(this)||c4(this))&&this.load()};
g.h.LK=function(){var a;this.K||c4(this)?a=f4(this,this.K):d4(this)&&(a=e4(this));if(this.B||this.H){for(var b=N2(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Rz(e),srclang:M2(e),id:e.toString()};this.H||(f.src=this.u.Bj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Md("TRACK",f))}a=this.T.app.B;a.dj(c);c=a.Za();this.na&&this.P.M(c.textTracks,"change",this.NK)}else!this.o&&a&&j4(this,a),this.player.ka("onCaptionsTrackListChanged"),this.player.ka("onApiChange")};
g.h.NK=function(){for(var a=this.T.app.B.Za().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=N2(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&j4(this,b,!0)};
g.h.tM=function(){!this.o&&this.B||this.unload()};
g.h.MK=function(a,b,c,d){if(a){this.u.Dy()&&(this.J=[],g.FQ(this.T.app,"captions",void 0),this.aa.bi(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.yv(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!S3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var v=a,z=c,C=d;if(!S3(v))throw Error("Invalid binary caption track data");e.o||(e.o=new Q3(C,b));var B=e.o.A(v,z)}else{if("WEBVTT"==a.substring(0,6)){b=a;z=c;e.o||(e.o=new V3);var G=e.o.A(b,z);.01>Math.random()&&
g.qo(Error("Deprecated subtitles format in web player: WebVTT"));v=G}else b:{G=a;z=g.d_(G);if(!z||!z.firstChild){var I=Error("Invalid caption track data");I.params=G;throw I;}if("timedtext"==z.firstChild.tagName){if(3==parseInt(z.firstChild.getAttribute("format"),10)){if(!e.o){G={};if(C=M2(b))G.lang=C,Opa.test(C)&&(G.pe=1);e.o=new D3(G,e.u)}v=e.o.A(z,c);break b}var F=Error("Unsupported subtitles format in web player (Format2)");F.params=G;throw F;}if("transcript"==z.firstChild.tagName){var M=Error("Unsupported subtitles format in web player (Format1)");
M.params=G;throw M;}var U=Error("Invalid caption track data");U.params=G;throw U;}B=v}var fa=B}catch(Ca){g.N(Ca),e.clear(),fa=[]}else fa=[];g.RK(this.player,fa);!this.K||this.H||g4(this)||g.kz(this.w)||g.lz(this.w)||(g.Zm(this.oa),fa=b3({Tf:0,Le:5,Dg:5,zk:2,textAlign:0,pe:0,lang:"en"}),this.V=[fa],e=["Click "," for settings"],this.ea||(B=new g.Hu(g.mM()),g.H(this,B),this.ea=B.element),B=fa.end-fa.start,(b=g.Rz(this.o))&&this.V.push(new Z2(fa.start,B,0,fa.id,b)),this.V.push(new Z2(fa.start,B,0,fa.id,
e[0]),new Z2(fa.start,B,0,fa.id,this.ea,!0),new Z2(fa.start,B,0,fa.id,e[1],!0)),g.RK(this.player,this.V),g.Xm(this.oa));!this.K||this.H||g4(this)||(i4(this,"module-enabled",!0),this.D&&(this.D.o=this.o),(fa=g.V(this.player.app))&&g.iI(fa.B));this.K=!1}};
g.h.pE=function(a){this.J.push(a);this.aa.bi()};
g.h.qE=function(a){g.ab(this.J,a);this.u instanceof V2&&this.u.C&&g.nT(this.player.app,[a],void 0);this.aa.bi()};
g.h.zL=function(a){if(a instanceof $2){var b=this.U[a.id];b&&b.A!=a&&(b.dispose(),delete this.U[a.id],b=null);b||(b=Npa(this,a))&&(this.U[a.id]=b)}else b=a.windowId,this.da[b]||(this.da[b]=[]),this.da[b].push(a)};
g.h.GL=function(){l4(this,this.V);this.V=null};
g.h.Sz=function(){this.aa.stop();g.Xb(this.da);this.J.sort(g.MD);var a=this.J;if(this.G){var b=(0,g.Td)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.zL,this);g.Ib(this.U,function(c,d){this.da[d]?(c.element.parentNode||g.VK(this.player,c.element,4),c.zh(this.da[d])):(c.dispose(),delete this.U[d])},this)};
g.h.LL=function(){$3(this,{},!0);g.R(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ka("captionssettingschanged")};
g.h.wC=function(){var a=k4.ub;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ke?3:a.bold?1:a.Ke?2:0,textOpacity:a.textOpacity,windowColor:k4.windowColor,windowOpacity:k4.windowOpacity};var b=a4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.Xz=function(a,b){var c={};g.Oa(c,a4(this,"display-settings"));g.Oa(c,a);$3(this,c,b);this.player.ka("captionssettingschanged")};
g.h.ts=function(){!this.B&&this.loaded&&(g.Ib(this.U,function(a,b){a.dispose();delete this.U[b]},this),this.Sz())};
g.h.uc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ld(b,-2,4);this.Xz({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&j4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.wb&&i4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Ka(b))break;if(g.Wb(b)){j4(this,null,!0);break}for(var d=N2(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.w!=b.languageName||(c=b.translationLanguage?xpa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||j4(this,c,!0)}else return this.loaded&&this.o&&!g4(this)?L2(this.o):{};return"";case "tracklist":return this.u?(0,g.ee)(N2(this.u.u,!(!b||!b.includeAsr)),function(k){return L2(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||m4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.wb&&a.push("stickyLoading");return a};
g.h.oE=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.nM=function(){this.loaded&&this.o&&!g4(this)?(i4(this,"module-enabled",!1),this.unload(),d4(this,!0)&&j4(this,e4(this),!1)):j4(this,g4(this)||!this.o?f4(this,!0):this.o,!0)};
g.h.GH=function(){var a=g4(this);d4(this,a)?j4(this,this.player.getAudioTrack().Tl,!1):this.S.captionTracks.length&&(this.loaded&&this.unload(),(this.fa?this.B||this.H:d4(this)||c4(this))&&(a?j4(this,f4(this),!1):this.load()))};g.OP.captions=b4;})(_yt_player);
